In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/spaceship-titanic/sample_submission.csv
/kaggle/input/spaceship-titanic/train.csv
/kaggle/input/spaceship-titanic/test.csv

In [2]:
# getting data

base_path = '../input/spaceship-titanic'
df_train = pd.read_csv(os.path.join(base_path,'train.csv'), index_col='PassengerId')
df_test  = pd.read_csv(os.path.join(base_path,'test.csv'), index_col='PassengerId')

In [3]:
df_train

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
PassengerId,,,,,,,,,,,,,
0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9276_01,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,False
9278_01,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,False
9279_01,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,True
9280_01,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False
9280_02,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True

In [4]:
df_test

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
PassengerId,,,,,,,,,,,,
0013_01,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning
0018_01,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers
0019_01,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus
0021_01,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter
0023_01,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez
...,...,...,...,...,...,...,...,...,...,...,...,...
9266_02,Earth,True,G/1496/S,TRAPPIST-1e,34.0,False,0.0,0.0,0.0,0.0,0.0,Jeron Peter
9269_01,Earth,False,NaN,TRAPPIST-1e,42.0,False,0.0,847.0,17.0,10.0,144.0,Matty Scheron
9271_01,Mars,True,D/296/P,55 Cancri e,NaN,False,0.0,0.0,0.0,0.0,0.0,Jayrin Pore
9273_01,Europa,False,D/297/P,NaN,NaN,False,0.0,2680.0,0.0,0.0,523.0,Kitakan Conale
9277_01,Earth,True,G/1498/S,PSO J318.5-22,43.0,False,0.0,0.0,0.0,0.0,0.0,Lilace Leonzaley

In [5]:
# seeing shapes!
print(f'train length: {df_train.shape}')
print(f'test length: {df_test.shape}')

train length: (8693, 13)
test length: (4277, 12)

In [6]:
df_train.describe()

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
count,8514.000000,8512.000000,8510.000000,8485.000000,8510.000000,8505.000000
mean,28.827930,224.687617,458.077203,173.729169,311.138778,304.854791
std,14.489021,666.717663,1611.489240,604.696458,1136.705535,1145.717189
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,19.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,38.000000,47.000000,76.000000,27.000000,59.000000,46.000000
max,79.000000,14327.000000,29813.000000,23492.000000,22408.000000,24133.000000

In [7]:
df_test.describe()

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
count,4186.000000,4195.000000,4171.000000,4179.000000,4176.000000,4197.000000
mean,28.658146,219.266269,439.484296,177.295525,303.052443,310.710031
std,14.179072,607.011289,1527.663045,560.821123,1117.186015,1246.994742
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,19.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,26.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,37.000000,53.000000,78.000000,33.000000,50.000000,36.000000
max,79.000000,11567.000000,25273.000000,8292.000000,19844.000000,22272.000000

In [8]:
df_train.columns.tolist()

['HomePlanet',
 'CryoSleep',
 'Cabin',
 'Destination',
 'Age',
 'VIP',
 'RoomService',
 'FoodCourt',
 'ShoppingMall',
 'Spa',
 'VRDeck',
 'Name',
 'Transported']

In [9]:
# selecting columns
columns = df_train.columns.tolist()
# ['HomePlanet', 'Destination', 'Age', 'VIP', 'RoomService', 'Transported']
train = df_train[columns]
test = df_test[columns[:-1]]

In [10]:
# printing NaN data count
print(train.isna().sum())
print()
print(test.isna().sum())

HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

HomePlanet       87
CryoSleep        93
Cabin           100
Destination      92
Age              91
VIP              93
RoomService      82
FoodCourt       106
ShoppingMall     98
Spa             101
VRDeck           80
Name             94
dtype: int64

### Working on categorical data

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
def grouping_categories(df_, col, labels, division=3):
    df = df_.copy(deep=True)
    min_value = df[col].min()
    max_value = df[col].max()
    step = np.round(max_value/division)
    intervals = np.arange( np.round(max_value), min_value, (-step), dtype=int)
    
    for i in range(len(labels)):
        df.loc[(df[col] < intervals[i]), f'{col}_Group'] = labels[i]
    
    return df

In [13]:
def labeling_data(df, columns):
    df_ = df.copy()
    for col in columns:
        if df_[col].dtypes != 'int64' and df_[col].dtypes != 'int32':
            le = LabelEncoder()
            df_[col] = le.fit_transform(df_[col])
    return df_

In [14]:
# grouping intervals
ages = ['Old', 'Adult', 'Young']
rooms = ['I', 'II', 'III', 'IV']
cols_todrop = ['Age', 'RoomService']

train = grouping_categories(train, cols_todrop[0], ages)
test = grouping_categories(test, cols_todrop[0], ages)
train = grouping_categories(train, cols_todrop[1], rooms, division=4)
test = grouping_categories(test, cols_todrop[1], rooms, division=4)

train.drop(columns=cols_todrop, inplace=True)
test.drop(columns=cols_todrop, inplace=True)

In [15]:
train.head()

,HomePlanet,CryoSleep,Cabin,Destination,VIP,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported,Age_Group,RoomService_Group
PassengerId,,,,,,,,,,,,,
0001_01,Europa,False,B/0/P,TRAPPIST-1e,False,0.0,0.0,0.0,0.0,Maham Ofracculy,False,Adult,IV
0002_01,Earth,False,F/0/S,TRAPPIST-1e,False,9.0,25.0,549.0,44.0,Juanna Vines,True,Young,IV
0003_01,Europa,False,A/0/S,TRAPPIST-1e,True,3576.0,0.0,6715.0,49.0,Altark Susent,False,Old,IV
0003_02,Europa,False,A/0/S,TRAPPIST-1e,False,1283.0,371.0,3329.0,193.0,Solam Susent,False,Adult,IV
0004_01,Earth,False,F/1/S,TRAPPIST-1e,False,70.0,151.0,565.0,2.0,Willy Santantines,True,Young,IV

In [16]:
test.head()

,HomePlanet,CryoSleep,Cabin,Destination,VIP,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Age_Group,RoomService_Group
PassengerId,,,,,,,,,,,,
0013_01,Earth,True,G/3/S,TRAPPIST-1e,False,0.0,0.0,0.0,0.0,Nelly Carsoning,Adult,IV
0018_01,Earth,False,F/4/S,TRAPPIST-1e,False,9.0,0.0,2823.0,0.0,Lerome Peckers,Young,IV
0019_01,Europa,True,C/0/S,55 Cancri e,False,0.0,0.0,0.0,0.0,Sabih Unhearfus,Adult,IV
0021_01,Europa,False,C/1/S,TRAPPIST-1e,False,6652.0,0.0,181.0,585.0,Meratz Caltilter,Adult,IV
0023_01,Earth,False,F/5/S,TRAPPIST-1e,False,0.0,635.0,0.0,0.0,Brence Harperez,Young,IV

In [17]:
# labeling categorical values
for c in cols_todrop:
    columns.remove(c)
    columns.append(f'{c}_Group')
labeled_train = labeling_data(train, columns)
labeled_test = labeling_data(test, test.columns)

In [18]:
labeled_train.head()

,HomePlanet,CryoSleep,Cabin,Destination,VIP,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported,Age_Group,RoomService_Group
PassengerId,,,,,,,,,,,,,
0001_01,1,0,149,2,0,0,0,0,0,5252,0,0,2
0002_01,0,0,2184,2,0,9,25,456,44,4502,1,2,2
0003_01,1,0,1,2,1,1206,0,1273,49,457,0,1,2
0003_02,1,0,1,2,0,806,332,1132,187,7149,0,0,2
0004_01,0,0,2186,2,0,69,149,470,2,8319,1,2,2

In [19]:
labeled_test.head()

,HomePlanet,CryoSleep,Cabin,Destination,VIP,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Age_Group,RoomService_Group
PassengerId,,,,,,,,,,,,
0013_01,0,1,2784,2,0,0,0,0,0,2912,0,2
0018_01,0,0,1867,2,0,9,0,724,0,2406,2,2
0019_01,1,1,257,0,0,0,0,0,0,3376,0,2
0021_01,1,0,259,2,0,843,0,155,359,2711,0,2
0023_01,0,0,1940,2,0,0,366,0,0,668,2,2

### Separating data

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
y = labeled_train['Transported']
X = labeled_train.drop(columns=['Transported'])
x_test = labeled_test.copy()

x_train, x_val, y_train, y_val = train_test_split(X, y, test_size=0.22, random_state=42)
print(f'x_train: {x_train.shape[0]}')
print(f'x_val: {x_val.shape[0]}')
print(f'x_test: {x_test.shape[0]}')

x_train: 6780
x_val: 1913
x_test: 4277

### Building Model

In [22]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import mean_squared_error

In [23]:
model = RandomForestClassifier(max_depth=15, n_estimators=500)

In [24]:
# training
model.fit(x_train, y_train)

RandomForestClassifier(max_depth=15, n_estimators=500)

In [25]:
model.score(x_val, y_val)

0.781495033978045

In [26]:
y_pred = model.predict(x_val)

mean_squared_error(y_val, y_pred)

0.21850496602195504

### Making prediction

In [27]:
preds = model.predict(x_test)
output = pd.DataFrame({'PassengerId': x_test.index.tolist(), 'Transported': preds.tolist()})
output['Transported'] = output['Transported'].apply(lambda x: bool(1) if x >= 0.5 else bool(0))
output.to_csv('submission.csv', index=False)
print(output)

     PassengerId  Transported
0        0013_01         True
1        0018_01        False
2        0019_01         True
3        0021_01         True
4        0023_01        False
...          ...          ...
4272     9266_02         True
4273     9269_01        False
4274     9271_01         True
4275     9273_01        False
4276     9277_01         True

[4277 rows x 2 columns]